repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
        exclude: .bumpversion.cfg
    -   id: end-of-file-fixer
        exclude: .bumpversion.cfg
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.13
    hooks:
    -   id: remove-tabs
        exclude: Makefile|.bumpversion.cfg
    -   id: remove-crlf
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        exclude: example/
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    -   id: flake8
        files: ^script/
